version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: tokio
    versions:
    - ">= 0.3.a, < 0.4"
  - dependency-name: hyper
    versions:
    - 0.14.4
    - 0.14.6
  - dependency-name: serde_json
    versions:
    - 1.0.62
    - 1.0.63
    - 1.0.64
  - dependency-name: tracing
    versions:
    - 0.1.24
    - 0.1.25
  - dependency-name: futures
    versions:
    - 0.3.12
    - 0.3.13
  - dependency-name: url
    versions:
    - 2.2.1
  - dependency-name: thiserror
    versions:
    - 1.0.24
  - dependency-name: tracing-futures
    versions:
    - 0.2.5
  - dependency-name: serde
    versions:
    - 1.0.123
  - dependency-name: rand
    versions:
    - 0.8.3
  - dependency-name: log
    versions:
    - 0.4.14
  - dependency-name: serde_yaml
    versions:
    - 0.8.16
  - dependency-name: tokio
    versions:
    - 1.1.1
