name: "Nix"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v12
      - uses: cachix/cachix-action@v7
        with:
          name: tapky6666
      - run: nix-build --no-out-link
